### ISSUE TITLE
Broken sqlite3 link

### ISSUE THREAD

**Issue by Binternet** [pelias/placeholder#103]
In the docs, the
https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/wof.sqlite3.gz

File is missing.

**Comment by missinglink** [comment]
Looks like a typo, thanks for letting us know, I'll open a PR to fix it shortly.

**Comment by missinglink** [comment]
FYI: you don't have to perform this step if you download the prebuilt `sqlite3` database directly with:

```
curl -s https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/store.sqlite3.gz | gunzip > data/store.sqlite3;
```

**Comment by Binternet** [comment]
Tried that and than ran the dockerfile [dockerfiles repo] and got:
`Error: Cannot find module '/data/placeholder/graph.json'`

**Comment by missinglink** [comment]
Can you please pull the latest docker image for placeholder and try again?

**Comment by Binternet** [comment]
Yup, works like a charm. thanks!
