### ISSUE TITLE
latest wof extract gzip not on public bucket

### ISSUE THREAD

**Issue by hardreddata** [pelias/placeholder#168]
Hey team! 

I was using your awesome geocoding engine (attempting to do Docker Pelias on Windows!) when I noticed something interesting.

Let me tell you more about it.

---
#### Here's what I did :innocent:

I tried to download https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/wof.extract.gz per the instructions in README.md

---
#### Here's what I got :scream_cat:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9A6265CC05A4764B</RequestId>
<HostId>
paHLZOXzVzWYUhwU/naNp3Cn3E/Z7BpKFsBkvgC3r6RgVFQgkuhUItHnAA3nOyDx8UVWobK97iA=
</HostId>
</Error>
```

---
#### Here's what I was expecting :sparkles:

Not that.

---
#### Here's what I think could be improved :trophy:

I was able to find some archives and note that http://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/archive/2019-01-28/wof.extract.gz downloads fine.

---
Not a huge deal but I thought you should know.

Cheers.

**Comment by missinglink** [comment]
Thanks for letting us know, we're trying to phase out the links to the nextzen bucket to help reduce the costs on the nextzen budget.

It could probably be provided with the other downloads at https://geocode.earth/data
