### ISSUE TITLE
The bucket was moved when mapzen closed down, the new URL is http://pelias-data.nextzen.org.s3.amazonaws.com/placeholder/store.sqlite3.gz

### ISSUE THREAD

**Issue by MLXKAS13** [pelias/placeholder#200]
The bucket was moved when mapzen closed down, the new URL is http://pelias-data.nextzen.org.s3.amazonaws.com/placeholder/store.sqlite3.gz

I'll update the docs.kristy you guys had fun to day

_Originally posted by @missinglink in https://github.com/pelias/placeholder/issues/95#issuecomment-381441008_

**Comment by missinglink** [comment]
Hi where is this referenced so we can update the docs?

**Comment by orangejulius** [comment]
Pretty sure this is spam. I've reported the account.
