### ISSUE TITLE
Docs say &layers= but actually &placetype=

### ISSUE THREAD

**Issue by azaroth42** [pelias/placeholder#202]
**Describe the bug**

The [documentation](https://github.com/pelias/documentation/blob/master/search.md#filter-by-data-type) says to use the  `layers` parameter to filter by the type of Feature. This does not make any difference to the results.

Instead it should be `placetype` (thanks to #55 for the hint on this)

**Comment by missinglink** [comment]
Hi @azaroth42, thanks for reaching out, `pelias/placeholder` (this repo) and [pelias/api](https://github.com/pelias/api) have different APIs.
You're absolutely right in noticing that the two repos have differing variables names for similar concepts.

The `pelias/api` parameter is named `layers`, this is a more generic term which allows us to include things which aren't only a 'placetype'.

The `pelias/placeholder` parameter is named `placetype`, this terminology is inherited from the [whosonfirst project](https://github.com/whosonfirst/whosonfirst-placetypes) and only refers to administrative areas (locality, state, country, etc) but not things like street,address which are valid 'layers' in the `pelias/api` vernacular.

I think the confusion lies in `pelias/placeholder` being a 'mircoservice' for `pelias/api` which I guess you could call the 'macroservice' here, it's the 'external API' of Pelias, whereas Placeholder is usually not exposed to the internet.

The [pelias/documentation](https://github.com/pelias/documentation) refers to the external API only and doesn't include any references to, or documentation for, internal services, for that it's best to refer to the [readme for this repo](https://github.com/pelias/placeholder#filtering-by-placetype).

**Comment by missinglink** [comment]
The easiest way of differentiating between the two is to check the URL path.

The `pelias/api` endpoints all start with `/v1` such as `/v1/search?text=YMCA&layers=venue,address` (in the docs)

IIRC all the `pelias/placeholder` endpoints all begin with `/parser/` such as `/parser/search`

They also run on different HTTP ports.

**Comment by azaroth42** [comment]
Should there be the link to `documentation` in the header of the readme then? That was where my confusion stemmed from -- now I do see the difference in the readme for `placetype`, thanks!
Or at least a warning to this effect?

**Comment by missinglink** [comment]
Agh yes, I see,  that's a standard header we use on all the repos, I can see how that's confusing 🙇 

<img width="204" alt="Screenshot 2021-08-09 at 17 16 01" src="https://user-images.githubusercontent.com/738069/128730302-8e6efeff-493e-4225-b7e8-685dc245f945.png">
