### ISSUE TITLE
socket hangup on 1 query

### ISSUE THREAD

**Issue by trescube** [pelias/placeholder#3]
When the API calls placeholder for this one query (repeatable):

９丁目, japan

it gets the following error:

2017-04-19T16:33:49.012Z - error: [placeholder] http://localhost:3000/parser/search?text=９丁目, Japan&lang=eng: {"code":"ECONNRESET"}
{ [Error: socket hang up] code: 'ECONNRESET' }

I'm unable to duplicate the error for similar neighbourhood inputs like "１丁目, Japan".

**Comment by orangejulius** [comment]
What ended up fixing this? (if anything)

**Comment by trescube** [comment]
Mysterious encoding issue when assembling the query manually.
