### ISSUE TITLE
Export skips files

### ISSUE THREAD

**Issue by dianashk** [pelias/placeholder#38]
While working on the docker-compose setup for Pelias, I came across this odd behavior and was able to confirm it outside of docker as well.

Here's a script I've used to reproduce it:

```bash
#!/bin/bash

mkdir -p ./test_build && cd ./test_build

git clone https://github.com/pelias/whosonfirst.git ./whosonfirst && cd ./whosonfirst;

git checkout filtered-download

npm install

echo \
'{
  "imports":{
    "whosonfirst": {
      "datapath": "../data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": true,
      "importPlace": "101715829",
      "api_key": "mapzen-fepXwQF"
    }
  }
}' > pelias.json

PELIAS_CONFIG=pelias.json npm run download

cd ..

git clone https://github.com/pelias/placeholder.git ./placeholder && cd ./placeholder;

npm install

mkdir -p ./data

WOF_DIR=../data/whosonfirst npm run extract

npm run build

echo "\033[31mCounts don't match up: \033[m"

find ../data/whosonfirst/data/ -name "*.geojson" | wc -l | awk '{print $1" wof records available"}'

wc -l ./data/wof.extract | awk '{print $1" lines in export"}'
```

in the end I'm getting the following counts consistently:

```
Counts don't match up: 
140 wof records available
33 lines in export
```

I've confirmed that the skipped WOF records are valid geojson files, so it's unclear why they are being skipped. Unfortunately, I couldn't make much sense of the *bash kung-fu* happening in wof_extract.sh.

**Comment by missinglink** [comment]
re: `postcodes`:

these are disabled from being imported in to `placeholder` due to the amount of RAM that is required for the whole planet. if you would like them imported you can edit the [placetype.filter](https://github.com/pelias/placeholder/blob/master/cmd/placetype.filter) and add any other placetypes you would like to import.

after setting `importPostalcodes: false` in my `~/pelias.json`:

```bash
$ find /tmp/wof -name "*.geojson" | wc -l
114
````

```bash
$ WOF_DIR=/tmp/wof npm run extract

> pelias-placeholder@0.0.0-semantic-release extract /var/www/pelias/placeholder
> bash cmd/wof_extract.sh > data/wof.extract

info: using parallel execution
```

```bash
$ wc -l data/wof.extract
114 data/wof.extract
```

I'm still wondering why you only get 33 records in your extract file?

**Comment by missinglink** [comment]
trying with postcodes this time, I `rm -rf` my data dir, enabled `importPostalcodes: true` and tried again:

```bash
$ find /tmp/wof -name "*.geojson" | wc -l
140
```

```bash
$ find /tmp/wof -name "*.geojson" | xargs grep -Poh 'wof:placetype":\s*\"(\K[^"]*)' | sort | uniq -c | sort -nr
    104 neighbourhood
     26 postalcode
      5 macrohood
      1 region
      1 locality
      1 county
      1 country
      1 continent
```

```bash
$ wc -l data/wof.extract
79 data/wof.extract
```

**Comment by missinglink** [comment]
agh right! figured it out, so what was happening is that as soon as `grep` found a placetype it didn't like, it would `exit 1` from that command, which in turn triggered `set -euo pipefail` and exited the whole extraction script after the first error.

I will put in a PR to fix it, this works with the original `placetype.filter` (114 records) and a `placetype.filter` with `postalcodes` added (140 records).

this bug will affect any data downloads which contain placetypes not in the default `placetype.filter`, the fix will simply skip over placetypes not specified in the filter.

FWIW: I really don't like the way `set -euo pipefail` fails silently but I couldn't find a way of making it more verbose.
