### ISSUE TITLE
remove dependency on gnu parallel

### ISSUE THREAD

**Issue by missinglink** [pelias/placeholder#44]
re: https://github.com/pelias/placeholder/blob/master/cmd/wof_extract.sh#L27-L44

apparently `xargs` supports parallel execution natively by passing it a parallel flag, so we can get rid of our external dependency on `parallel`

**Comment by Joxit** [comment]
Using the command `xargs -n 1 -P +0` can do the trick but this will not keep data order and that's what paralell is doing now.
Is the order of the data important for the extract?

**Comment by missinglink** [comment]
The data order is not important.
