### ISSUE TITLE
cast numeric strings to floats

### ISSUE THREAD

**Issue by missinglink** [pelias/placeholder#6]
in some cases, WOF encodes numeric fields as strings eg:

```javascript
"geom:latitude": -41.072228,
"geom:longitude": 145.907314,
"lbl:latitude": "-41.0690002441",
"lbl:longitude": "145.895690918",
```

since the data is stored verbatim in the internal `store` it might be nicer to explicitly cast these strings to floats in `prototype/wof.js`:

```javascript
  // --- cast float ---
  // note: sometimes numeric properties in WOF can be encoded as strings.

  if( 'string' === typeof doc.geom.area ){ doc.geom.area = parseFloat( doc.geom.area ); }
  if( 'string' === typeof doc.geom.lat ){ doc.geom.lat = parseFloat( doc.geom.lat ); }
  if( 'string' === typeof doc.geom.lon ){ doc.geom.lon = parseFloat( doc.geom.lon ); }
```

**Comment by missinglink** [comment]
I started writing the tests for this when I remembered @trescube was working on something similar, do you already have some tests for `prototype/wof.js` that I can expand upon?

**Comment by trescube** [comment]
I have not gotten around to writing any unit tests for placeholder but I've modified the API to account for this:  https://github.com/pelias/api/pull/850/commits/df549dfb02cbfbf344c9b2f9a32969f825871ae5

**Comment by missinglink** [comment]
opened issue upstream: https://github.com/whosonfirst-data/whosonfirst-data/issues/787

**Comment by missinglink** [comment]
this issue has already been resolved upstream!
