### ISSUE TITLE
CI tests can only ever pass on the same day new data is pushed

### ISSUE THREAD

**Issue by orangejulius** [pelias/placeholder#60]
https://github.com/pelias/placeholder/blob/master/.travis.yml#L14-L18 shows that Travis downloads data with the current date in the URL. However, we don't, and probably don't want to, push new data to S3 every day. This means tests will fail on most days.

Ideally the tests are separated into unit/functional tests that have their own mock data and can run without downloading any data.

**Comment by missinglink** [comment]
Good point, in this case we could fall back to using the current production data for builds.

**Comment by missinglink** [comment]
The `aria2c` command supports fallback urls, I'm not sure if `curl` does without additional scripting.

**Comment by orangejulius** [comment]
Falling back to the current production data sounds like a decent solution. checking the status code with `curl -I` could be used to determine whether falling back makes sense. It would still be a bit of scripting but could be done.
