### ISSUE TITLE
All access to this object has been disabled

### ISSUE THREAD

**Issue by karussell** [pelias/placeholder#95]
When I tried to run this project, I got:
```xml
<Error><Code>AllAccessDisabled</Code><Message>All access to this object has been disabled</Message><RequestId>209B3AEF9974EC5D</RequestId><HostId>Jpt3vmeNjQDfLcMQBYzTdlww2TgxsrcdVewfj91ktm4JX6Dr+OzjEVNTFTheEynpOVmgoUEUeFA=</HostId></Error>
```

for 

$ curl -s http://pelias-data.s3.amazonaws.com/placeholder/store.sqlite3.gz

**Comment by missinglink** [comment]
The bucket was moved when mapzen closed down, the new URL is http://pelias-data.nextzen.org.s3.amazonaws.com/placeholder/store.sqlite3.gz

I'll update the docs.

**Comment by karussell** [comment]
Thanks!

**Comment by karussell** [comment]
now I get: 

Connecting to pelias-data.nextzen.org.s3.amazonaws.com (pelias-data.nextzen.org.s3.amazonaws.com)|52.216.165.179|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-04-16 10:08:25 ERROR 403: Forbidden.

**Comment by orangejulius** [comment]
Oops, I forgot to set all the files to public :)

https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/store.sqlite3.gz works now

**Comment by MLXKAS13** [comment]
kristy you guys had fun

**Comment by star958** [comment]
Other reason： overdue account is disabled because arrears.

**Comment by missinglink** [comment]
This url has changed a few times over the years, the current url is https://data.geocode.earth/placeholder/store.sqlite3.gz

**Comment by racertracy** [comment]
qnbvxdcpj@wzfh47drsylsnep3ys.cbmmldqxt.drivefact.org
